### ISSUE TITLE
PHP 8 Deprecation notices

### ISSUE THREAD

**Issue by biggeeves** [grezniczek/redcap-qrcode#4]
On PHP 8.1 there are several deprecation notices:

- Deprecated - Optional parameter $record declared before required parameter $event_id is implicitly treated as a required parameter, File: modules/redcap_qrcode_v1.0.2/QRCodeExternalModule.php, Line: 18
- Deprecated - Optional parameter $record declared before required parameter $survey_hash is implicitly treated as a required parameter, File: modules/redcap_qrcode_v1.0.2/QRCodeExternalModule.php, Line: 28
- Deprecated - Optional parameter $group_id declared before required parameter $survey_hash is implicitly treated as a required parameter, File: modules/redcap_qrcode_v1.0.2/QRCodeExternalModule.php, Line: 28
- Deprecated - Optional parameter $record declared before required parameter $event_id is implicitly treated as a required parameter, File: modules/redcap_qrcode_v1.0.2/QRCodeExternalModule.php, Line: 35
- Deprecated - preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated, File: modules/redcap_qrcode_v1.0.2/QRCodeExternalModule.php, Line: 86

The following error may be related to the EM and the library?

- Error message: Warning - file_put_contents(redcap_v13.1.32/Libraries/phpqrcode/cache/frame_4.dat): Failed to open stream: No such file or directory, File: redcap_v13.1.32/Libraries/phpqrcode/qrspec.php, Line: 568
- Error message: Warning - mkdir(): No such file or directory, File: redcap_v13.1.32/Libraries/phpqrcode/qrmask.php, Line: 154
- Error message: Warning - file_put_contents(redcap_v13.1.32/Libraries/phpqrcode/cache/mask_0/mask_33_0.dat): Failed to open stream: No such file or directory, File: redcap_v13.1.32/Libraries/phpqrcode/qrmask.php, Line: 155

**Comment by grezniczek** [comment]
@biggeeves - 1.0.2 is quite outdated and not compatible with REDCap >= 13.1.0

Updating to 1.1.0 should fix all this.
