### ISSUE TITLE
Error message: Deprecated - preg_match_all() on line 83

### ISSUE THREAD

**Issue by biggeeves** [grezniczek/redcap-qrcode#6]
Error message: Deprecated - preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated, File: /var/www/html/modules/redcap_qrcode_v1.2.2/QRCodeExternalModule.php, Line: 83

might be fixed by adding a line above it:
if(is_null($misc)) {continue;}

Which would continue the loop:
foreach ($Proj->forms[$instrument]["fields"] as $fieldName => $_) {

**Comment by grezniczek** [comment]
@biggeeves - Thanks for reporting. Fixed via c0c40d0256072690fa92a4dd3f0dcc7e6d5a9e17
