### ISSUE TITLE
Enhancement: use label instead of value if  @QRCODE source is a for radio, multichoice, etc type of field. 

### ISSUE THREAD

**Issue by aboulang** [grezniczek/redcap-qrcode#7]
I think this picture indicates the need, The current behavior is the value 1 is encoded instead of what ID [record-name] Sex [sex] Size [size] PMI [pmi] resolves to.  (This is to get around the limitation of values are always used in @CALCTEXT).

![image](https://github.com/user-attachments/assets/c59e5320-25ca-46fe-aee0-33a02a856b3f)

**Comment by grezniczek** [comment]
This is a limitation of CALCTEXT. You should petition for CALCTEXT to support this, on the Community forum.

**Comment by aboulang** [comment]
@grezniczek, I am deliberately not using CALCTEXT in the fields shown. instead, I am trying to pick up the label of the choice.

**Comment by grezniczek** [comment]
@aboulang - You could use `@PREFILL` (on a regular text box), which supports piping, together with `@READONLY`, and instruct users to _Save & Stay_ if any data from the current form is to be used in the QR code (you might hide the field showing the QR code by some branching logic that depends on a field on some other form that calculates the shown/hidden state based on all the "necessary ingredients".

The way QR code works in the background does not fit well with piping directly into it.

You could also look at the Barcodes EM, but this will need the same workaround as mentioned above.

**Comment by aboulang** [comment]
@grezniczek  SETVALUE, aka PREFILL, sets the value upon load and you set up the barcode on save.. I tried SETVALUE prior, but I think two saves needs to happen before the barcode gets to display the right values?

My solution was to punt the whole issue and recode all the fields so the coded value reflects the pretty value.

Type of package
Big_Size, Big Size
Even_More_Stuff, Even More Stuff

**Comment by grezniczek** [comment]
If you don't need the QR code as a file, but only for display on the page, then have a look at the Barcodes EM. Then 1x save should be enough.
